config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'  

  match '/index' => 'home#index', as: 'index', via:[:get, :post]
  match '/homepage' => 'home#homepage', as: 'homepage', via:[:get, :post]
  
  match '/init_event' => 'home#init_event', as: 'init_event', via:[:get, :post]
  match '/update_event' => 'home#update_event', as: 'update_event', via:[:get, :post]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base

	attr_accessible :customer_name, :telephone, :address, :zipcode

	has_many :event
end

app/models/employee.rb
class Employee < ActiveRecord::Base

	attr_accessible :employee_name, :telephone, :address, :zipcode

	has_many :event
end

app/models/event.rb
class Event < ActiveRecord::Base

	attr_accessible :employee_id, :customer_id, :product_id, :event_comment, :reserve_start_at, :reserve_end_at

	belongs_to :employee
	belongs_to :customer
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base

    attr_accessible :image_address, :unit, :amount, :price, :product_name

	has_many :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #
  protect_from_forgery with: :exception
  before_filter :miniprofiler
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  private

  def miniprofiler
    Rack::MiniProfiler.authorize_request # if user.admin?
  end
end

app/controllers/calendars.rb
class Calendars
  
  def self.init
    start_day = 2.months.ago
    end_day = 2.months.from_now 
    event = Event.where(:reserve_start_at=>start_day..end_day)
    result = []
    event.map do |e|
      t = e.product
      te = e.employee
      tc = e.customer
      result.push e.attributes.slice("id","reserve_start_at","reserve_end_at","employee_id","customer_id","product_id", "event_comment").merge("product_name"=>t.product_name, "price"=>t.price,"employee_name"=>te.employee_name,"customer_name"=>tc.customer_name)
    end
    return result
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		# Rack::MiniProfiler.step("homepage in the index function") do
		# 	if params.has_key?(:flag)
		# 		render "index"
		# 	elsif user_signed_in?
		# 			redirect_to action:'homepage'
		# 	end
		# end
	end

	def init_event
    respond_to do |format|
      format.json { 
        render json: Calendars.init
      }
    end
	end

	def update_event
		if params.has_key?(:id) and params.has_key?(:start) and params.has_key?(:product_id) and params.has_key?(:end) and params.has_key?(:employee_id) and params.has_key?(:customer_id) and params.has_key?(:event_comment)
			temp = Event.find(params[:id].to_i)
			begin
				# logger.debug(temp)
				# temp.update_attributes(:employee_id=>params[:employee_id].to_i, :customer_id=>params[:customer_id].to_i, :product_id=>params[:product_id].to_i)
				# logger.debug(params[:id])
				temp.update_attributes(:employee_id=>params[:employee_id].to_i, :customer_id=>params[:customer_id].to_i, :product_id=>params[:product_id].to_i, :event_comment=>params[:event_comment].to_s, :reserve_start_at=>params[:start].to_time, :reserve_end_at=>params[:end].to_time)
				result = "Success"
			rescue
				result = "Fail"
			end
			respond_to do |format|
				format.json {
					render json: {result: result}
				}
			end
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/homepage.html.erb
<p>Hello, here is the homepage.</p>
<% if user_signed_in? %>
    <li><%= link_to t(:logout), destroy_user_session_path, :method=>'delete' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
  <li><%= link_to t(:logout), destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
  <li><%= link_to t(:login), homepage_path %></li>
  <% end %>
  <li><%= link_to t(:home), index_path %></li>
  <li><a data-toggle="modal" href="#help"><%=t(:help)%></a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>潘氏一理 * 23周年</title>
	<link rel="icon" type="image/png" href="assets/images/other_images/favicon_girl.png">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- IE9 form fields placeholder fix -->
    <!--[if lt IE 9]>
    <script>contact_form_IE9_placeholder_fix();</script>
    <![endif]-->  

        <!-- background image fix for IE 9 or less
       - use same background as set above to <body> -->
    <!--[if lt IE 9]>
    <script type="text/javascript">
    $(document).ready(function(){
      jQuery("#outer-background-container").backstretch("assets/images/other_images/bg5.jpg");
    });
    </script> 
    <![endif]-->  
	<%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
	<div class="navbar-collapse collapse">
		<div  class="container-fluid position-center">
			<%= render 'layouts/navigation' %>
		</div>
	</div>
	<div class="container-fluid">
		<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
	</div>
	<%= yield %>
	<%= yield(:place_for_modal) %>
</body>
</html>